--- # DELEGATE TO FUNCTION DEMO 
- hosts: apacheweb 
  sudo: yes
  user: ansible
  connection: ssh
  tasks: 
   - name: Run a remote ping on the application server 
     command: ping -c 4 ansible.client.elantecs.com > /tmp/ping_deleagteto.out
     delegate_to: 127.0.0.1
   - name: Install a package
     yum: pkg=lynx state=latest
     

