--- # FULL INCLUDE TASKS EXAMPLE
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - include: plays/packages.yml
    - name: Verify the telnet package is installed
      raw: yum list installed | grep telnet > /home/ansible/pkgs_telnet.logs
    - name: Verify the lynx package is installed
      raw: yum list installed | grep lynx > /home/ansible/pkgs_lynx.logs
