--- # My First YAML Playbook for Ansible NOTIFY
- hosts: apacheweb
  user: ansible 
  sudo: yes
  connection: ssh
  gather_facts: no 
  vars:
    playbook_version: 0.1b
  vars_files:
   - conf/copyright.yml
   - conf/webdefaults.yml
  vars_prompt:
    - name: web domain
      prompt: Web Domain
  tasks:
    - name: Install Apache Web Browser
      action: yum name=httpd state=installed
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD 
      action: service name=httpd state=restarted 
