--- # TAG FUNCTIONALITY EXAMPLE
- hosts: apacheweb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install the telnet and Lynx packages
      yum: pkg={{ item }} state=latest
      with_items:
         - telnet
         - lynx
      tags:
         - packages
    - name: Verify that telent was installed
      raw: yum list installed | grep telnet > /home/ansible/pkg_telnet_tags.log
    - name: Verify that lynx was installed
      raw: yum list installed | grep lynx > /home/ansible/pkg_lynx_tags.log
      tags:
         - verification
