---
- hosts: apacheweb
  become: yes
  user: ansible
  connection: ssh
  vars: 
   description: "{{ ansible_hostname }} 
  tasks: 
  - name: install apache
    yum: 
     name: httpd  
     state: latest
  - name: write the index file
    template: src=template.j2 dest=/var/www/html/index.html
    notify:
    - restart httpd
  - name: ensure apache is running
    service: name=httpd state=running
